#!/usr/bin/env python3
"""Generate remaining EnergieMIND locale files."""
import json
import copy
from pathlib import Path

MESSAGES = Path("/workspace/messages")
with open(MESSAGES / "en.json", encoding="utf-8") as f:
    EN = json.load(f)

PRESERVE = {
    "enm.contractAddress": "0x00faB8baFfF3f849dd23FF68cfE51d8E3d09937D",
    "contact.email": "contact@energiemind.com",
}


def merge(base, overrides):
    r = copy.deepcopy(base)
    for k, v in overrides.items():
        if k in r and isinstance(r[k], dict) and isinstance(v, dict):
            r[k] = merge(r[k], v)
        else:
            r[k] = v
    return r


def b(overrides):
    return merge(EN, overrides)


LOCALES = {
    "tr": b({
        "meta": {"title": "EnergieMIND — Yapay Zeka Destekli Enerji Zekası", "description": "EnergieMIND; enerji sistemlerini, madencilik ısı geri kazanımını, yapay zeka optimizasyonunu ve sürdürülebilir altyapıyı tek bir akıllı enerji katmanında birleştirir."},
        "nav": {"home": "Ana Sayfa", "mission": "Misyon", "energyIntelligence": "Enerji Zekası", "miningHeatUtility": "Madencilik Isı Kullanımı", "technology": "Teknoloji", "pilotProgram": "Pilot Program", "ecosystem": "Ekosistem", "enmToken": "ENM Token", "roadmap": "Yol Haritası", "contact": "İletişim"},
        "hero": {"subheadline": "Madencilik ısı kullanımı, sürdürülebilir altyapı ve geleceğin enerji ağları için yapay zeka destekli enerji zekası.", "supporting": "Enerji Zekası · Madencilik Isı Geri Kazanımı · Yapay Zeka Optimizasyonu · Sürdürülebilir Altyapı · ENM Utility Katmanı", "ctaExplore": "EnergieMIND'ı Keşfedin", "ctaPilot": "Pilot Fırsatlarını Görüşün", "ctaToken": "ENM Token Bilgilerini Görüntüleyin"},
        "mission": {"subtitle": "Enerji, madencilik, yapay zeka ve sürdürülebilirliği birleştirmek", "description": "EnergieMIND; enerji sistemlerini, madencilik sistemlerini, yapay zeka koordinasyonunu ve sürdürülebilirliği tek bir akıllı enerji altyapısı konseptinde birleştirir. Hesaplama enerjisi, geri kazanılan ısı ve altyapı zekasının birlikte çalıştığı koordinasyon katmanını geliştiriyoruz.", "pageTitle": "Misyonumuz", "pageIntro": "EnergieMIND, enerji ve madencilik sistemlerinin etkileşimini dönüştürmek için tasarlandı — boşa giden hesaplama enerjisini faydalı ısı, zeka ve sürdürülebilir altyapı değerine dönüştürüyor.", "visionTitle": "Vizyon", "visionText": "Her joule hesaplama enerjisinin akıllıca koordine edildiği bir gelecek — binalar, çiftlikler ve enerji ağları için hash gücü, geri kazanılabilir ısı, operasyonel veri ve optimizasyon fırsatları üreten.", "approachTitle": "Yaklaşım", "approachText": "Enerji izleme, yapay zeka destekli optimizasyon, madencilik ısı geri kazanımı ve sürdürülebilir altyapı tasarımını birleşik bir enerji zekası platformunda birleştiriyoruz — şu anda geliştirme ve pilot hazırlık aşamasında."},
        "problem": {"title": "Sorun", "subtitle": "Enerji sistemlerinde koordinasyon ve zeka eksikliği var", "items": {"wastedEnergy": "Enerji üretim, dağıtım ve tüketimde boşa gidiyor.", "wastedHeat": "Madencilik ısısı boşa giderken ticari binalar ısınmaya ihtiyaç duyuyor.", "noIntelligence": "Enerji sistemlerinde gerçek zamanlı zeka ve koordinasyon eksik.", "infrastructure": "Altyapının enerji, ısı ve hesaplama arasında daha iyi koordinasyona ihtiyacı var."}},
        "thesis": {"title": "EnergieMIND Tezi", "subtitle": "Hesaplama enerjisi boşa gitmemeli", "description": "Madencilik makineleri hash gücünden daha fazlasını üretebilir. EnergieMIND, hesaplama enerjisi altyapısının tüm değer zincirini yakalamak ve koordine etmek için tasarlandı.", "outputs": {"hashPower": "Ağ güvenliği için hash gücü", "heat": "Binalar ve tesisler için geri kazanılabilir ısı", "data": "Operasyonel ve enerji performans verileri", "metrics": "Gerçek zamanlı operasyonel metrikler", "optimization": "Enerji optimizasyon fırsatları"}},
        "pillars": {"title": "Temel Sütunlar", "subtitle": "Beş birbirine bağlı enerji zekası katmanı", "energyIntelligence": {"title": "Enerji Zekası", "description": "Madencilik, ısıtma ve altyapı sistemlerinde enerji akışlarının yapay zeka destekli izlenmesi, analizi ve optimizasyonu."}, "miningHeatUtility": {"title": "Madencilik Isı Kullanımı", "description": "Madencilik ısısının evler, oteller, çiftlikler ve ticari tesisler için kullanımı — hesaplama yan ürününü faydalı termal enerjiye dönüştürme."}, "energyDashboard": {"title": "Enerji Paneli", "description": "Enerji tüketimi, madenci çıktısı, ısı geri kazanım oranları ve operasyonel performansın tek bir görünümde izlenmesi."}, "sustainableInfrastructure": {"title": "Sürdürülebilir Altyapı", "description": "Yenilenebilir enerji, madencilik operasyonları, ısıtma sistemleri ve enerji verimliliğinin koordineli altyapıda birleştirilmesi."}, "enmUtilityLayer": {"title": "ENM Utility Katmanı", "description": "Ekosistem kullanımı için gelecekteki tokenize koordinasyon katmanı — EnergieMIND enerji ağına katılımı sağlar."}},
        "pilot": {"title": "Pilot Program", "subtitle": "Gelecekteki ticari pilotlar için tasarlandı", "description": "EnergieMIND, çeşitli tesis türleri için pilot fırsatları hazırlıyor. Madencilik ısı kullanımı ve enerji zekasıyla ilgilenen kuruluşlar için çözümler geliştiriyoruz.", "targets": {"hotels": "Oteller", "commercial": "Ticari Binalar", "greenhouses": "Seralar", "farms": "Çiftlikler", "solar": "Güneş Enerjisi Sahaları", "industrial": "Endüstriyel Tesisler", "mining": "Madencilik Tesisleri", "datacenters": "Veri Merkezleri"}, "pageTitle": "Pilot Program", "pageIntro": "EnergieMIND pilot hazırlık aşamasında. Madencilik ısı geri kazanımı, enerji zekası ve yapay zeka destekli optimizasyondan yararlanabilecek tesisler için dağıtım modelleri tasarlıyoruz.", "cta": "Pilot Fırsatlarını Görüşün"},
        "ecosystem": {"title": "Ekosistem", "subtitle": "TVK / EnteleKRON ekosisteminin parçası", "description": "EnergieMIND, güven, yapay zeka ve altyapıdan oluşan daha geniş bir ekosistem içindeki enerji zekası ve sürdürülebilir altyapı katmanıdır.", "layers": {"tvk": {"role": "Holding Katmanı"}, "infrasphere": {"role": "Altyapı Katmanı"}, "sovra": {"role": "Yapay Zeka Zekası Katmanı"}, "entelekron": {"role": "Güven Katmanı"}, "energiemind": {"role": "Enerji Zekası Katmanı"}, "enm": {"role": "Utility Token Katmanı"}}, "pageTitle": "Ekosistem", "pageIntro": "EnergieMIND, TVK / EnteleKRON ekosisteminde enerji zekası katmanı olarak çalışır — altyapı, yapay zeka, güven ve utility koordinasyonunu birleştirir."},
        "enm": {"title": "ENM Token", "subtitle": "EnergieMIND ekosistemi için utility katmanı", "description": "ENM, EnergieMIND katmanı için hazırlanan Ethereum ERC-20 tokenidir. Ekosistem içinde utility koordinasyon tokeni olarak tasarlanmıştır — yatırım ürünü değildir.", "contract": "Sözleşme Adresi", "riskNotice": "Risk Bildirimi", "riskText": "ENM, EnergieMIND ekosisteminde bir utility tokenidir. Yatırım ürünü değildir. Token değerleri dalgalanabilir. Getiri vaat edilmez. Riskleri anladıktan sonra katılın. Tam token ve ön satış detayları enm.network adresinde mevcuttur.", "cta": "ENM Network'e Git", "pageTitle": "ENM Token Bilgileri", "pageIntro": "ENM, EnergieMIND ekosistemi için utility token katmanı olarak hizmet verir. Tam token detayları, ön satış bilgileri ve dokümantasyon için enm.network adresini ziyaret edin.", "utilityTitle": "Utility Amacı", "utilityText": "ENM, ekosistem utility koordinasyonu için tasarlanmıştır — EnergieMIND enerji zekası ağına katılımı sağlar. Yatırım aracı olarak sunulmaz.", "disclaimerTitle": "Önemli Sorumluluk Reddi", "disclaimerText": "Bu sayfa yalnızca temel sözleşme bilgileri sağlar. EnergieMIND.com enerji zekası projesine odaklanır. Tüm detaylı token bilgileri, ön satış detayları ve risk açıklamaları enm.network adresinde tutulur."},
        "roadmap": {"title": "Yol Haritası", "subtitle": "Geliştirme kilometre taşları", "pageTitle": "Yol Haritası", "pageIntro": "EnergieMIND geliştirmesi aşamalı bir yaklaşım izler — konsept ve mimariden pilot hazırlığına ve gelecekteki dağıtıma kadar.", "phases": {"phase1": {"title": "Faz 1 — Konsept ve Mimari", "status": "Devam Ediyor", "items": "Enerji zekası konsept geliştirme, ekosistem mimarisi tasarımı, madencilik ısı kullanımı araştırması"}, "phase2": {"title": "Faz 2 — Teknoloji Geliştirme", "status": "Geliştiriliyor", "items": "Enerji paneli geliştirme, yapay zeka optimizasyon modülleri, ısı geri kazanım sistemi tasarımı"}, "phase3": {"title": "Faz 3 — Pilot Hazırlığı", "status": "Planlandı", "items": "Pilot saha belirleme, tesis değerlendirmesi, dağıtım modeli tasarımı"}, "phase4": {"title": "Faz 4 — Ticari Pilotlar", "status": "Gelecek", "items": "Otel, ticari bina ve tarımsal tesis pilotları, performans doğrulaması"}, "phase5": {"title": "Faz 5 — Ağ Genişlemesi", "status": "Gelecek", "items": "Çoklu saha koordinasyonu, ENM utility katmanı aktivasyonu, ekosistem entegrasyonu"}}},
        "contact": {"title": "İletişim", "subtitle": "EnergieMIND ile iletişime geçin", "pageTitle": "İletişim", "pageIntro": "Pilot fırsatları, ortaklıklar veya EnergieMIND hakkında daha fazla bilgi mi istiyorsunuz? Enerji zekası ve madencilik ısı kullanımını keşfeden kuruluşlardan gelen talepleri memnuniyetle karşılıyoruz.", "pilotInquiry": "Pilot Program Talepleri", "pilotText": "Madencilik ısı kullanımı ve enerji zekası sistemlerinin gelecekteki pilot dağıtımlarıyla ilgilenen kuruluşlar için.", "partnershipInquiry": "Ortaklık Talepleri", "partnershipText": "Ekosistem içindeki altyapı ortakları, enerji şirketleri ve teknoloji entegratörleri için.", "generalInquiry": "Genel Talepler", "generalText": "EnergieMIND, ekosistem veya teknoloji geliştirme hakkında genel sorular için.", "tokenNote": "ENM token'e özel talepler için lütfen enm.network adresini ziyaret edin"},
        "energyIntelligence": {"pageTitle": "Enerji Zekası", "pageIntro": "Enerji akışlarının yapay zeka destekli izlenmesi ve optimizasyonu — madencilik, ısıtma ve altyapı sistemlerine zeka getirmek için tasarlandı.", "section1Title": "Gerçek Zamanlı İzleme", "section1Text": "EnergieMIND, bağlı altyapıda enerji tüketimi, üretimi ve optimizasyon fırsatlarını izleyen paneller ve izleme sistemleri geliştiriyor.", "section2Title": "Yapay Zeka Destekli Optimizasyon", "section2Text": "Enerji kalıplarını analiz etmek, talebi tahmin etmek ve madencilik ile ısıtma sistemleri için operasyonel programları optimize etmek üzere tasarlanmış makine öğrenimi modelleri.", "section3Title": "Altyapı Koordinasyonu", "section3Text": "Yenilenebilir enerji kaynakları, madencilik operasyonları ve ısıtma talebini koordineli bir enerji zekası ağında birleştirme."},
        "miningHeatUtility": {"pageTitle": "Madencilik Isı Kullanımı", "pageIntro": "Hesaplama yan ürününü binalar, çiftlikler ve ticari tesisler için faydalı termal enerjiye dönüştürme.", "section1Title": "Isı Geri Kazanım Konsepti", "section1Text": "Madencilik donanımı önemli termal çıktı üretir. EnergieMIND, bu ısıyı yakalamak ve ısınmaya ihtiyaç duyan tesislere yönlendirmek için tasarlandı — oteller, seralar, ticari binalar ve tarımsal operasyonlar.", "section2Title": "Çift Değerli Madencilik", "section2Text": "Isıyı atık olarak görmek yerine, madencilik operasyonları hem hesaplama çıktısı hem de faydalı termal enerji üretebilir — genel enerji verimliliğini artırır.", "section3Title": "Tesis Entegrasyonu", "section3Text": "Mevcut HVAC altyapısıyla entegrasyon için tasarlanmış ısı geri kazanım sistemleri, büyük tesis değişiklikleri olmadan madencilik ısı kullanımını sağlar."},
        "technology": {"pageTitle": "Teknoloji", "pageIntro": "EnergieMIND'ın teknik temeli — enerji panelleri, yapay zeka optimizasyonu, ısı geri kazanım sistemleri ve altyapı koordinasyonu.", "section1Title": "Enerji Paneli Platformu", "section1Text": "Bağlı altyapıda enerji akışlarını, madenci performansını, ısı geri kazanım oranlarını ve sistem sağlığını izlemek için tasarlanmış birleşik bir izleme platformu.", "section2Title": "Yapay Zeka Optimizasyon Motoru", "section2Text": "Madencilik ve ısıtma sistemlerinde enerji kalıbı analizi, talep tahmini ve operasyonel program optimizasyonu için makine öğrenimi modülleri.", "section3Title": "Isı Geri Kazanım Sistemleri", "section3Text": "Madencilik ısısını bağlı tesislere yakalamak ve dağıtmak için mühendislik tasarımları — doğrudan hava ısıtmasından su bazlı ısı değişim sistemlerine kadar.", "section4Title": "Altyapı API'leri", "section4Text": "Yenilenebilir enerji sistemlerini, madencilik donanımını, ısıtma altyapısını ve ENM utility katmanını bağlamak için tasarlanmış entegrasyon arayüzleri."},
        "footer": {"tagline": "Sürdürülebilir altyapı için yapay zeka destekli enerji zekası.", "rights": "Tüm hakları saklıdır.", "legal": "EnergieMIND gelişmekte olan bir enerji zekası projesidir. Yatırım getirisi vaat edilmez. ENM token detayları enm.network adresinde tutulur."},
        "common": {"learnMore": "Daha Fazla Bilgi", "backToHome": "Ana Sayfaya Dön", "selectLanguage": "Dil Seçin", "statusDeveloping": "Geliştiriliyor", "statusPlanned": "Planlandı", "statusFuture": "Gelecek", "statusInProgress": "Devam Ediyor"},
    }),
}

# Write only tr for now - script will be extended
for loc, data in LOCALES.items():
    with open(MESSAGES / f"{loc}.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Wrote {loc}.json")
